# Generated by Django 4.0.2 on 2022-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculator',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='phonecode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='sortname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
