# Generated by Django 4.0.2 on 2022-02-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_rename_calculator_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phonecode',
        ),
        migrations.RemoveField(
            model_name='country',
            name='sortname',
        ),
    ]
