# Generated by Django 4.0.2 on 2022-02-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_country_phonecode_remove_country_sortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('days', models.CharField(blank=True, max_length=10, null=True)),
                ('kg05', models.FloatField(blank=True, default=0, null=True)),
                ('kg1', models.FloatField(blank=True, default=0, null=True)),
                ('kg2', models.FloatField(blank=True, default=0, null=True)),
                ('kg3', models.FloatField(blank=True, default=0, null=True)),
                ('kg4', models.FloatField(blank=True, default=0, null=True)),
                ('kg5', models.FloatField(blank=True, default=0, null=True)),
                ('kg6', models.FloatField(blank=True, default=0, null=True)),
                ('kg7', models.FloatField(blank=True, default=0, null=True)),
                ('kg8', models.FloatField(blank=True, default=0, null=True)),
                ('kg9', models.FloatField(blank=True, default=0, null=True)),
                ('kg10', models.FloatField(blank=True, default=0, null=True)),
                ('kg11', models.FloatField(blank=True, default=0, null=True)),
                ('kg12', models.FloatField(blank=True, default=0, null=True)),
                ('kg13', models.FloatField(blank=True, default=0, null=True)),
                ('kg14', models.FloatField(blank=True, default=0, null=True)),
                ('kg15', models.FloatField(blank=True, default=0, null=True)),
                ('kg16', models.FloatField(blank=True, default=0, null=True)),
                ('kg17', models.FloatField(blank=True, default=0, null=True)),
                ('kg18', models.FloatField(blank=True, default=0, null=True)),
                ('kg19', models.FloatField(blank=True, default=0, null=True)),
                ('kg20', models.FloatField(blank=True, default=0, null=True)),
                ('kg_21_44', models.FloatField(blank=True, default=0, null=True)),
                ('kg_45_70', models.FloatField(blank=True, default=0, null=True)),
                ('kg_71_100', models.FloatField(blank=True, default=0, null=True)),
                ('kg_101_299', models.FloatField(blank=True, default=0, null=True)),
                ('kg_300_plus', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
